### ISSUE TITLE
[BUG] loopPages fades out on fast swipe

### ISSUE THREAD

**Issue by Exocomp** [fermoya/SwiftUIPager#233] opened 2021-08-30 19:55 UTC
**Describe the bug**
Swiping fast (forward direction) with loopPages results in content completely fading out with no way to recover.

**To Reproduce**
- Use the loopPages option
- SwiftUIPager/Example/SwiftUIPagerExample/Examples/InfiniteExampleView.swift

**Expected behavior**
When swiping fast (forward direction) with the loopPages option the content fading out with no way to recover.

**Screenshots / Videos**
See attached video.

**Environment:**

https://user-images.githubusercontent.com/25571083/131396830-a137104a-8c71-4e83-af33-6cbf54d499c4.mov

 - iOS 14.6
 - Device iPhone7 Plus
- SwiftUIPager version 2.3.1

**Additional context**
n/a.

**Comment by fermoya** [comment] 2021-08-30 21:15
Hi @Exocomp , thanks for your feedback. How many elements you have? It varies depending on the device, the issue you mention is known and there’s currently no fix for that.

If you notice the docs for that modifier:
> To have a nice experience, ensure that  the `data` passed in the intializer has enough elements to fill pages on both the screen and the sides. If your sequence is not large enough, use `count` to repeat it and pass more elements.

The workaround would be to use `.loopPages(repeating: 2)` or higher.

**Comment by Exocomp** [comment] 2021-08-30 21:52
Hi @fermoya ,

It's with 10 items but I also I tested with higher like 100 with the same result.

`var items = Array(0..<100)`

I also tried:

`.loopPages(repeating: 2)`

It still has the same exact problem. Swiping fast just wants to fade out.

Any other ideas?

**Comment by fermoya** [comment] 2021-09-09 19:12
@Exocomp unfortunately I don't there's any other workaround. `loopPages` simply doesn't work well with `multiplePagination`

There's no fix for now, unfortunately. The issue here is that when `Pager` is looping the elements get reordered. When the scroll is slow, those elements that get off screen on one side won't appear on the other side but if you scroll fast enough that produces a weird effect where you see the elements moving sideways. The workaround for that is [here](https://github.com/fermoya/SwiftUIPager/blob/168614398b1986a6e07060d5d127122643cfe724/Sources/SwiftUIPager/PagerContent.swift#L164). The logic around `isEdgePage` is prone to errors if the scroll of fast enough, that's why the elements disappear.

The fix for this would be either to improve that method or find a better workaround for that...

**Comment by fermoya** [comment] 2021-11-15 21:06
@paulfreeman yes, apologies. For some reason I thought this was referring to `multiplePagination`. I'll add that extra check, this is just a problem when `multiplePagination` is enabled

**Comment by fermoya** [comment] 2021-11-16 09:33
I take it back, that's actually a problem with or without `multiplePagination`. I'll need to revisit the algorithm

**Comment by darecki** [comment] 2022-03-18 15:48
@fermoya do you know why it works flawlessly when scrolling left? This issue occurs only when scrolling right. It's interesting...

**Comment by fermoya** [comment] 2022-03-23 20:01
It's probably something to do with the current implementation. It's not the best work I've done, I'll tell you that. I need to review it but that takes time.

Problem is elements get rearranged because the elements displayed change the order. So for instance, if you're showing 1 2 3 after swiping you should va e 3 2 1. In that transition, the element at the very left moves to the right in a weird effect, that's why I hide it. But perhaps there's a better solution, perhaps there's a better way for `ForEach` to handle this or it shouldn't be displayed in the first place.

Going in one direction or another night influence in that the implementation might be more permissive in one direction or because of the way the elements are arranged. Say the number of elements is even, it might be the case that there are more elements loaded in one side or the other

**Comment by fermoya** [comment] 2022-03-25 20:53
this should be fixed [here](https://github.com/fermoya/SwiftUIPager/releases/tag/2.3.3-beta.3):
https://github.com/fermoya/SwiftUIPager/releases/tag/2.3.3-beta.3

**Comment by darecki** [comment] 2022-03-28 10:26
I can confirm the issue is fixed! Thanks for that :)

**Closed** 2022-03-30 11:42 UTC
Labels: bug
