### ISSUE TITLE
List in Pager: Scrolling issue for vertical list in horizontal pager 

### ISSUE THREAD

**Issue by i-vivek** [fermoya/SwiftUIPager#27] opened 2020-04-07 00:50 UTC
I'm trying to achieve card view with list inside pager view. I'm facing scrolling issue because of gesture. swipeGesture is getting detected even if I scroll vertically in List.

Here is demo code:

```
struct ContentView: View {
    @State var pageIndex = 0
    var colors: [Color] = [
        .red, .blue, .black, .gray, .purple, .green, .orange, .pink, .yellow, .white
    ]
    
    var body: some View {
        VStack {
            Pager(page: self.$pageIndex, data: self.colors, id: \.self) { color in
                ZStack {
                    RoundedRectangle(cornerRadius: 8)
                        .foregroundColor(color)
                    VStack(alignment: .leading) {
                        Text("Today").padding()
                        List(0..<100) { num in
                            Text("\(num)")
                        }.padding()
                    }
                }
            }
            .itemSpacing(16)
            .padding(24)
            .interactive(0.95)
        }
    }
}
```
![ezgif-6-d5c316130c84](https://user-images.githubusercontent.com/42919970/78619907-b5fddd00-78d2-11ea-9c8e-f500c8bb1829.gif)
Compare with App Store : ![ezgif-6-688945432a99](https://user-images.githubusercontent.com/42919970/78619752-5273af80-78d2-11ea-8e30-eead5aa1671b.gif)

It is lagging in performance, not responding well when you scroll list at first time. Later it will work.

**Comment by fermoya** [comment] 2020-04-07 07:53
Duplicate of #18

**Comment by fermoya** [comment] 2020-04-07 07:56
Hi @i-vivek ,

It's a known issue that unfortunately the framework has. At the moment, I haven't found a way to cancel the gesture if the touch is a vertical swipe (considering the pager is horizontal). There doesn't seem to be a good way to do this, for now.

I've marked it as duplicate as there's a related issue involving a scroll view and the problem is basically the same, several gestures at the same time. Feel free to peek the code and contribute if you think there's a good way to do this.

Thanks

**Closed by fermoya** 2020-04-07 07:56 UTC
